// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } 
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoNaZwdlkJOkBFdNRpEwEz7dgeWD_QUnU',
    appId: '1:362434696100:web:adcff0a6069efb15c0e731',
    messagingSenderId: '362434696100',
    projectId: 'flowsnap-1e47e',
    authDomain: 'flowsnap-1e47e.firebaseapp.com',
    storageBucket: 'flowsnap-1e47e.firebasestorage.app',
    measurementId: 'G-WSH86Z6FEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXU2LErCo8T0a9fge0I3xW2ZoZUkN_e_k',
    appId: '1:362434696100:android:13b9cc404924a852c0e731',
    messagingSenderId: '362434696100',
    projectId: 'flowsnap-1e47e',
    storageBucket: 'flowsnap-1e47e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY53pwfoBvvBqk7vZRERp7QYhlPhRwgPU',
    appId: '1:362434696100:ios:046ab1ab77633262c0e731',
    messagingSenderId: '362434696100',
    projectId: 'flowsnap-1e47e',
    storageBucket: 'flowsnap-1e47e.firebasestorage.app',
    iosClientId: '362434696100-e2nsulau92hbrp84fhhhgk1vrvrems3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY53pwfoBvvBqk7vZRERp7QYhlPhRwgPU',
    appId: '1:362434696100:ios:046ab1ab77633262c0e731',
    messagingSenderId: '362434696100',
    projectId: 'flowsnap-1e47e',
    storageBucket: 'flowsnap-1e47e.firebasestorage.app',
    iosClientId: '362434696100-e2nsulau92hbrp84fhhhgk1vrvrems3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoNaZwdlkJOkBFdNRpEwEz7dgeWD_QUnU',
    appId: '1:362434696100:web:c39acf21a5b9ae81c0e731',
    messagingSenderId: '362434696100',
    projectId: 'flowsnap-1e47e',
    authDomain: 'flowsnap-1e47e.firebaseapp.com',
    storageBucket: 'flowsnap-1e47e.firebasestorage.app',
    measurementId: 'G-1CGNS2X804',
  );

}